_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 35
                - 55
            "4": 3.11.0
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
action_noise:
    value: null
batch_size:
    value: 128
buffer_size:
    value: 300000
ent_coef:
    value: auto
env_seed:
    value: 666
gamma:
    value: 0.98
gradient_steps:
    value: 20
learning_rate:
    value: 0.001
learning_starts:
    value: 30000
model_seed:
    value: 666
normalactionnoise:
    value: null
optimize_memory_usage:
    value: true
policy:
    value: MlpPolicy
policy_kwargs:
    value:
        activation_fn: relu
        log_std_init: np.log(0.5)
        net_arch:
            pi:
                - 128
                - 128
            qf:
                - 256
                - 256
        optimizer_class: adam
        optimizer_kwargs:
            amsgrad: true
replay_buffer_class:
    value: null
replay_buffer_kwargs:
    value: null
sde_sample_freq:
    value: -1
sigma:
    value: 0.1
stats_window_size:
    value: 100
target_update_interval:
    value: 1
tau:
    value: 0.02
train_freq:
    value: 20
use_sde:
    value: false
use_sde_at_warmup:
    value: false
