_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 35
                - 55
            "4": 3.11.0
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
batch_size:
    value: 128
clip_range:
    value: 0.2
ent_coef:
    value: 0.05434
env_seed:
    value: 666
gae_lambda:
    value: 0.9167
gamma:
    value: 0.9631
learning_rate:
    value: 2e-05
max_grad_norm:
    value: 0.3
model_seed:
    value: 666
n_epochs:
    value: 8
n_steps:
    value: 2048
normalize_advantage:
    value: true
policy:
    value: MlpPolicy
policy_kwargs:
    value:
        activation_fn: silu
        log_std_init: np.log(1)
        net_arch:
            pi:
                - 256
                - 256
                - 256
            vf:
                - 512
                - 512
                - 512
        optimizer_class: adam
        optimizer_kwargs:
            amsgrad: true
sde_sample_freq:
    value: 8
target_kl:
    value: null
use_sde:
    value: false
vf_coef:
    value: 0.8225
