# Description: Configuration file for the Egypt environment
# Always define the general parameters for the base environment
GreenLightEnv:
  weather_data_dir: gl_gym/environments/weather # path to weather data
  location: Egypt             # location of the recorded weather data
  num_params: 208                 # number of model parameters
  nx: 28                          # number of states
  nu: 6                           # number of control inputs
  nd: 10                          # number of weather disturbances
  dt: 900                         # [s] time step for the underlying GreenLight solver
  u_min: [0, 0, 0, 0, 0, 0]
  u_max: [1, 1, 1, 1, 1, 1]
  delta_u_max: 0.1                # max change rate in control inputs
  pred_horizon: 0.5               # [days] number of future weather predictions
  season_length: 60               # number of days to simulate
  start_train_year: 2024          # start year for training
  end_train_year: 2024            # end year for training
  start_train_day: 59             # start day of the year for training
  end_train_day: 59               # end day of the year for training  
  training: True                  # whether we are training or testing

LettuceEnv:
  reward_function: GreenhouseReward       # reward function to use

  observation_modules: [                  # observation modules to use
    IndoorClimateObservations,   
    BasicCropObservations, 
    ControlObservations, 
    WeatherObservations,
    TimeObservations,
    WeatherForecastObservations
  ]

  constraints:
    co2_min: 300.         # lower bound on CO2 concentration                [ppm]        0
    co2_max: 1300 #1600.        # upper bound on CO2 concentration              [ppm]        2.75e-3
    temp_min: 15.         # lower bound on temperature                    [°C]         6.5
    temp_max:  28 #34.         # upper bound on temperature                    [°C]        20
    rh_min: 50.            # lower bound on relative humidity             [#]          0
    rh_max: 85.          # upper bound on relative humidity               [#]         70

  eval_options:
    eval_days: [59]                    # days to evaluate the agent on
    eval_years: [2024]                  # year to evaluate the agent on
    location: Egypt                 # location of the greenhouse

  reward_params:
    fixed_greenhouse_cost: 15.
    fixed_co2_cost: 0.015
    fixed_lamp_cost: 0.07       # in reality this is multiplied by the max used intensity of the lamps e.g., 200umol/m2/s (we do the same.)
    fixed_screen_cost: 2.       # 1,- per screen
    elec_price: 0.3             # €/kWh
    heating_price: 0.09         # €/kWh
    co2_price: 0.3              # €/kg
    fruit_price: 1.2 #1.6            # €/kg
    dmfm: 0.05 #0.065                 # dry matter fresh matter ratio
    pen_weights: [4.e-4, 5.e-3, 7.e-4]
    pen_lamp: 0.1

# results_columns: [
#   Time, co2_air, co2_top, temp_air, temp_top, can_temp, covin_temp, covex_temp,
#   thScr_temp, flr_temp, pipe_temp, soil1_temp, soil2_temp, soil3_temp, soil4_temp, soil5_temp, 
#   vp_air, vp_top, lamp_temp, intlamp_temp, grow_pipe_temp, blscr_temp, 24_can_temp,
#   cBuf, cleaves, cstem, cFruit, tsum, glob_rad, temp_out, rh_out, co2_out, wind_speed,
#   heating_setpoint, co2_setpoint, thr_scr, vent_setpoint, lamp,
#   profits, cum_profits, cum_fixed_costs, cum_var_costs, cum_gains, episode
#]





# اعتمدت التعديلات علي بيانات من مصادر موثوقه حول الشروط البيئيه المثاليه للخس في البيوت الزجاجيه,
# مثل نطاق درجات الحراره (18-24 درجه مئويه عاده لذا حد الاقصي 28),
# تركيز CO2(حتي 1300 PPM),
# نسبه الماده الجافه (حوالي 5%)
# وسعر الخس (حوالي 1.2 يورو/كجم بناء علي اسعار الجمله في اوروبا)


#  النطاق الأمثل لدرجة الحرارة النهارية يتراوح بين 18-24 درجة مئوية،
#  بينما الليلية حوالي 13-18 درجة مئوية. يمكن للخس تحمل درجات حرارة أعلى مؤقتًا،
#  لكن النمو يتباطأ فوق 24 درجة مئوية، وقد يحدث الإزهار المبكر (bolting) عند الاقتراب من 30 درجة مئوية أو أكثر،
#  وقد يموت النبات عند 37-40 درجة مئوية. لذلك، تم تعديل الحد الأعلى (temp_max) إلى 28 درجة مئوية كقيد آمن لتجنب الأضرار،
